name: re-wild-oasis - dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            --secret id=env,src=.env \
            -t re-wild-oasis .

      - name: Stop existing container
        run: |
          docker stop re-wild-oasis || true
          docker rm re-wild-oasis || true

      - name: Run new container
        run: |
          docker run -d \
            --name re-wild-oasis \
            --restart unless-stopped \
            -p 8082:80 \
            re-wild-oasis

      - name: Check container
        run: |
          docker ps --filter "name=re-wild-oasis"