name: re-wild-oasis - dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Backup current image
        run: |
          docker tag re-wild-oasis:current re-wild-oasis:backup || true

      - name: Build new docker image
        run: |
          docker build \
            --secret id=env,src=/home/venom/Projects/re-wild-oasis/.env \
            -t re-wild-oasis:new .

      - name: Stop existing container
        run: |
          docker stop re-wild-oasis || true
          docker rm re-wild-oasis || true

      - name: Run new container
        run: |
          docker run -d \
            --name re-wild-oasis \
            --restart unless-stopped \
            -p 8082:80 \
            re-wild-oasis:new

      - name: Health check
        id: health
        run: |
          echo "Waiting for application startup..."
          sleep 5

          curl --fail http://localhost:8082

          echo "Application is healthy"
      
      - name: Promote new image
        if: success()
        run: |
          docker tag re-wild-oasis:new re-wild-oasis:current
          docker rmi re-wild-oasis:new || true
      
      - name: Rollback on failure
        if: failure()
        run: |
          echo: 'Deployment failed. Rolling back...'

          docker stop re-wild-oasis || true
          docker rm re-wild-oasis || true

          docker run -d \
            --name re-wild-oasis \
            --restart unless-stopped \
            -p 8082:80 \
            re-wild-oasis:backup